export enum SWRUniqueKey {
  Logs = "logs",
  Users = "users",
  Department = "department",
  Tels = "tels",
  NetworkType = "networkType",
  NetworkTypeLevel = "networkTypeLevel",
  Liner = "liner",
  IpAddress = "ipAddress",
  Documents = "documents",
  DocumentDetail = "documentDetail",
  Topologys = "topologys",
  DeviceBase = "deviceBase",
  DeviceOptions = "deviceOptipns",
  DeviceSummary = "deviceSummary",
  NetworkTypeSummary = "networkTypeSummary",
}
